version: '1.0'

services:
  cqrs-postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: lender_groups
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    volumes:
      - "./db:/docker-entrypoint-initdb.d"